### ISSUE TITLE
Sophus version

### ISSUE THREAD

**Issue by RayTang88** [SJTU-ViSYS/Ground-Fusion#2]
@sjtuyinjie @SJTU-ViSYS 
Thanks for your open source code！
Now I am going to compile it on arm, but I have encountered some errors. I guess it is the problem of sophus version, or can you help me to see what is the problem?
The current version of sophus I use is 1.22.10.

![image](https://github.com/SJTU-ViSYS/Ground-Fusion/assets/42015878/30a62fd3-a697-47f9-b5f7-7ecb4a96560a)

Thank you very much!

**Comment by sjtuyinjie** [comment]
Glad to help. You need to install the non-template version Sophus. Look up to https://blog.csdn.net/qq_40574123/article/details/122764225 for reference.

**Comment by RayTang88** [comment]
Thank you for you replay！
If I use non-template version Sophus, the following error occurs when I look at the header file of non-template version Sophus ending in  .h. Have you ever encountered this problem?
![image](https://github.com/SJTU-ViSYS/Ground-Fusion/assets/42015878/45c11a7b-3292-4daa-a274-738599c87e58)

If I used template version Sophus, I would get a header ending in.hpp, but I wouldn't get libSophu.so.

If I use template version Sophus, I get a header ending in.hpp, then I use non-template version Sophus to get libSophu.so, and I can compile normally, and I'm wondering is that correct?

Thank you very much!

**Comment by sjtuyinjie** [comment]
This is right
