### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by zuowei1998** [SJTU-ViSYS/Ground-Fusion#3]
can you help me to see what is the problem? thanks in advance.
![1ecbed3c-1db1-49fe-885b-028146ebe435](https://github.com/SJTU-ViSYS/Ground-Fusion/assets/50592247/a7f6ddc5-8108-4654-9674-c1509cb7a2a7)

**Comment by sjtuyinjie** [comment]
It seems to be problems with dependency libffi. You can check it
