### ISSUE TITLE
关于请教轮速打滑检测

### ISSUE THREAD

**Issue by Sunshinehaozi** [SJTU-ViSYS/Ground-Fusion#4]
您好，感谢您开源如此具有意义的工作。

- 我正在学习轮速打滑检测方案，看到您们论文中提到关于轮速打滑检测是采用“轮速预积分值 与 imu预积分值”进行比较，从而判断是否出现打滑，但我在看代码的时候发现轮速打滑检测实际上是使用的如下的代码
- double dis = (dP_wheel - dP_imu).norm();
- 此处dP_wheel dp_imu 个人认为并不是轮速 && imu的位置预积分值
- dp_Wheel dp_imu的计算方式如下
-         dP_imu = dP_imu + dt * Vs[j] + 0.5 * dt * dt * un_acc;
-         dP_wheel[0] -= dt * Vs[j][1];
          dP_wheel[1] += dt * Vs[j][0];
          dP_wheel[2] -= dt * Vs[j][2];
- 个人认为轮速的位置预积分值应该是
- 
![图片](https://github.com/SJTU-ViSYS/Ground-Fusion/assets/33956988/2e8fece8-5f10-45ce-a17b-9c713560c1f4)

- 个人认为IMU的位置预积分值应该是
- 
![图片](https://github.com/SJTU-ViSYS/Ground-Fusion/assets/33956988/1309ec19-adbb-40c5-9f38-91f7322a5213)

我暂时未能理解 dp_Wheel dp_imu 所表达的涵义，向请教一下dp_wheel dp_imu代表什么意思呢？
另外想确认下，上述图片箭头所指的值是否 就是对应的IMU位置预积分值 以及 轮速的位置预积分值。

希望不吝赐教呀！

**Comment by sjtuyinjie** [comment]
你可以看一下这行代码：Vs[j] = 0.5 * latest_sv * (Rs[j] * linear_velocity + un_vel_0);
注意Vs在这里获取了轮速预测的body系的速度，这里也是在做预积分。
Vs被多次赋值过，确实容易混淆，你可以再看看
