### ISSUE TITLE
GTK+ 2.x symbols detected

### ISSUE THREAD

**Issue by Amber016** [SJTU-ViSYS/Ground-Fusion#6]
您的论文写的太棒了，已经多次阅读，祝贺你取得如此瞩目的成果，吾辈楷模！！
我在运行您的代码时遇到了部分问题，想请您解答，我已在网上找了很多方法未果，只能麻烦您了，非常感谢。
我已编译完成，但在运行时遇到了这个问题：（vins_node:130331): Gtk-ERROR **: 10:18:24.765: GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported
![Screenshot from 2024-05-09 10-18-41](https://github.com/SJTU-ViSYS/Ground-Fusion/assets/50046055/da595798-8fa2-4b4e-8069-5a62881ba9a4)

感谢解答，祝科研顺利，成果多多！

**Comment by sjtuyinjie** [comment]
这个错误信息表明你的程序中同时使用了GTK+ 2和GTK+ 3。
首先，你需要确定是哪个部分或哪个依赖库引起了这种冲突。你可以检查依赖库，看看哪些链接到GTK+ 2.x和GTK+ 3。
然后，统一GTK+版本，再重新编译试试。
祝你好运~
